title    Rigel 1 «Orion» — ядро LTS (%ARCH%, UEFI)
sort-key 02
linux    /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux-lts
initrd   /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux-lts.img
options  archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% %KERNEL_PARAMS%
