APP_ID=dev
APP_TAB=pro
APP_TITLE="Разработка"
APP_DESC="Git, Neovim, компиляторы, контейнеры и популярные языки."
APP_ONLINE=1
APP_PACKAGES="git neovim cmake gdb podman docker python nodejs npm rustup go jdk-openjdk"
